# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  pmbudgetapi:
    image: pmbudgetapi
    build:
      context: ./src
      dockerfile: ./pmBudget.API/Dockerfile
    ports:
      - 7047:7047
      - 5047:5047
    depends_on:
      - postgres
    volumes:
      - ./src:/app
    networks:
      - pmbudget-network
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Master@2022
      POSTGRES_DB: pmBudget
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pmbudget-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com.br'
      PGADMIN_DEFAULT_PASSWORD: 'Admin@2021!'
    ports:
      - 16544:80
    depends_on:
      - postgres
    networks:
      - pmbudget-network

volumes:
  postgres-data:

networks:
  pmbudget-network: