# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  pmbudgetapi:
    image: pmbudgetapi
    build:
      context: .
      dockerfile: src/pmBudget.API/Dockerfile
    ports:
      - 5047:5047
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
